#!/bin/bash

##This is a good exemple of a single-process multi-threaded job

#SBATCH -p regular 		# partition name
#SBATCH -c 8 		# number of cores or threads requested -- this needs to be greater than or equal to the number of cores/threads you plan to use to run your job
#SBATCH --job-name bowtie2-mapHS 		# Job name
#SBATCH -o %j.out			# File to which standard out will be written
#SBATCH -e %j.err 		# File to which standard err will be written
#SBATCH --mem 60G

## Changing directories to where the fastq files are located
cd /cscratch/fastq_files

##loading Bowtie2 module (check 'module spider fastqc to get the exact module name to load)
module load Bowtie2


## Set fastq files to use as variables
in1=./*_R1_unmap_CQ.fastq.gz
in2=./*_R2_unmap_CQ.fastq.gz

## Set name of output file
out=./output_HS.sam


##bowtie2 command line to map reads against human genome.
bowtie2 --very-sensitive-local --threads 8 --reorder --seed 4 -x ./results/bowtie2-build-HS/Homo_sapiens -1 $in1  -2 $in2 -S $out



