#!/bin/bash

##This is a good exemple of a single-process multi-threaded job

#SBATCH -p regular 		# partition name
#SBATCH -c 8 		# number of cores or threads requested -- this needs to be greater than or equal to the number of cores/threads you plan to use to run your job
#SBATCH --job-name bowtie2-map1 		# Job name
#SBATCH -o %j.out			# File to which standard out will be written
#SBATCH -e %j.err 		# File to which standard err will be written
#SBATCH --mem 20G

## Changing directories to where the fastq files are located
cd /cscratch/fastq_files

##loading Bowtie2 module (check 'module spider fastqc to get the exact module name to load)
module load Bowtie2

##Set fastq files that will be used to run the command
R1=/*1P.fastq.gz
R2=/*2P.fastq.gz
## set output file name
output=output_CP

##bowtie2 command line to map reads against C. pipiens database
bowtie2 --very-sensitive-local --threads 8 --reorder --seed 4 -x ./results/bowtie2-build-demo01/culex_pipiens -1 $R1  -2 $R2 -S ./5_L1/${output}.sam



