#!/bin/bash

##This is a good exemple of a single-process multi-threaded job

#SBATCH -p regular 		# partition name
#SBATCH -c 8 		# number of cores or threads requested -- this needs to be greater than or equal to the number of cores/threads you plan to use to run your job
#SBATCH --job-name bowtie2-build-CQ 		# Job name
#SBATCH -o %j.out			# File to which standard out will be written
#SBATCH -e %j.err 		# File to which standard err will be written
##SBATCH -t 01:30:00 # Run time (hh:mm:ss) - 1.5 hours
#SBATCH --mem 60G

## Changing directories to where the fastq files are located
cd /cscratch/fastq_files

##loading bowtie2 module 
module load Bowtie2

##Create results subdirectory
mkdir -p ./results/bowtie2-build-CQ/

##bowtie2 command line with fna file from C. quinquefasciatus
bowtie2-build --threads 8 --seed 4 GCF_015732765.1_VPISU_Cqui_1.0_pri_paternal_genomic.fna ./results/bowtie2-build-CQ/culex_quinquefasciatus



