#!/bin/bash

##This is a good exemple of a single-process multi-threaded job

#SBATCH -p regular 		# partition name
#SBATCH -c 8 		# number of cores or threads requested -- this needs to be greater than or equal to the number of cores/threads you plan to use to run your job
#SBATCH --job-name samtools-bam2fastq-SORT 		# Job name
#SBATCH -o %j.out			# File to which standard out will be written
#SBATCH -e %j.err 		# File to which standard err will be written
##SBATCH -t 01:30:00 # Run time (hh:mm:ss) - 1.5 hours
#SBATCH --mem 40G

## Changing directories to where the fastq files are located
##cd /cscratch/mibanez/results/
##cd /cscratch/mibanez/results/bowtie2-mapHS
cd /cscratch/mibanez/11_L1/

##loading fastqc module (check 'module spider fastqc to get the exact module name to load)
module load SAMtools

##Create results subdir
##mkdir -p unmapped_fastq2

## Set files to be used with command
in=11_sorted.bam
out1=11_R1_unmap_def.fastq.gz
out2=11_R2_unmap_def.fastq.gz

##samtools command line
samtools fastq -@ 8 $in -1 $out1 -2 $out2 

