#!/bin/bash

##This is a good exemple of a single-process multi-threaded job

#SBATCH -p regular 		# partition name
#SBATCH -c 8 		# number of cores or threads requested -- this needs to be greater than or equal to the number of cores/threads you plan to use to run your job
#SBATCH --job-name samtools-bam2fastq-SORT 		# Job name
#SBATCH -o %j.out			# File to which standard out will be written
#SBATCH -e %j.err 		# File to which standard err will be written
##SBATCH -t 01:30:00 # Run time (hh:mm:ss) - 1.5 hours
#SBATCH --mem 40G

## Changing directories to where the fastq files are located
cd /cscratch/fastq_files

##loading SAMtools module (check 'module spider fastqc to get the exact module name to load)
module load SAMtools



## Set files to be used with command
in=/*_sorted.bam
out1=/*_R1_unmap_def.fastq.gz
out2=/*_R2_unmap_def.fastq.gz

##samtools command line to transform bam file to separated fastq files.
samtools fastq -@ 8 $in -1 $out1 -2 $out2 

