#!/bin/bash

##This is a good exemple of a single-process multi-threaded job

#SBATCH -p regular 		# partition name
#SBATCH -c 8 		# number of cores or threads requested -- this needs to be greater than or equal to the number of cores/threads you plan to use to run your job
#SBATCH --job-name samtools-bam2fastq-SORT 		# Job name
#SBATCH -o %j.out			# File to which standard out will be written
#SBATCH -e %j.err 		# File to which standard err will be written
##SBATCH -t 01:30:00 # Run time (hh:mm:ss) - 1.5 hours
#SBATCH --mem 40G

## Changing directories to where the fastq files are located
cd /cscratch/fastq_files

##loading SAMtools module 
module load SAMtools


## Define input and output files
in=unmap_*.bam
out=*_sorted.bam


##samtools command line to sort bam file
samtools sort -n $in -o $out


